/* This file was generated by SableCC (http://www.sablecc.org/). */

package equivalence.parser;

import equivalence.node.*;
import equivalence.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTParallel(@SuppressWarnings("unused") TParallel node)
    {
        this.index = 0;
    }

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 1;
    }

    @Override
    public void caseTNil(@SuppressWarnings("unused") TNil node)
    {
        this.index = 2;
    }

    @Override
    public void caseTSemi(@SuppressWarnings("unused") TSemi node)
    {
        this.index = 3;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 4;
    }

    @Override
    public void caseTBang(@SuppressWarnings("unused") TBang node)
    {
        this.index = 5;
    }

    @Override
    public void caseTSend(@SuppressWarnings("unused") TSend node)
    {
        this.index = 6;
    }

    @Override
    public void caseTQuery(@SuppressWarnings("unused") TQuery node)
    {
        this.index = 7;
    }

    @Override
    public void caseTReceive(@SuppressWarnings("unused") TReceive node)
    {
        this.index = 8;
    }

    @Override
    public void caseTOn(@SuppressWarnings("unused") TOn node)
    {
        this.index = 9;
    }

    @Override
    public void caseTX(@SuppressWarnings("unused") TX node)
    {
        this.index = 10;
    }

    @Override
    public void caseTY(@SuppressWarnings("unused") TY node)
    {
        this.index = 11;
    }

    @Override
    public void caseTZ(@SuppressWarnings("unused") TZ node)
    {
        this.index = 12;
    }

    @Override
    public void caseTH(@SuppressWarnings("unused") TH node)
    {
        this.index = 13;
    }

    @Override
    public void caseTCnot(@SuppressWarnings("unused") TCnot node)
    {
        this.index = 14;
    }

    @Override
    public void caseTMeasure(@SuppressWarnings("unused") TMeasure node)
    {
        this.index = 15;
    }

    @Override
    public void caseTNewqubit(@SuppressWarnings("unused") TNewqubit node)
    {
        this.index = 16;
    }

    @Override
    public void caseTIf(@SuppressWarnings("unused") TIf node)
    {
        this.index = 17;
    }

    @Override
    public void caseTThen(@SuppressWarnings("unused") TThen node)
    {
        this.index = 18;
    }

    @Override
    public void caseTElse(@SuppressWarnings("unused") TElse node)
    {
        this.index = 19;
    }

    @Override
    public void caseTInput(@SuppressWarnings("unused") TInput node)
    {
        this.index = 20;
    }

    @Override
    public void caseTOutput(@SuppressWarnings("unused") TOutput node)
    {
        this.index = 21;
    }

    @Override
    public void caseTPrint(@SuppressWarnings("unused") TPrint node)
    {
        this.index = 22;
    }

    @Override
    public void caseTAssign(@SuppressWarnings("unused") TAssign node)
    {
        this.index = 23;
    }

    @Override
    public void caseTLparen(@SuppressWarnings("unused") TLparen node)
    {
        this.index = 24;
    }

    @Override
    public void caseTRparen(@SuppressWarnings("unused") TRparen node)
    {
        this.index = 25;
    }

    @Override
    public void caseTIntlit(@SuppressWarnings("unused") TIntlit node)
    {
        this.index = 26;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 27;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 28;
    }
}
