/* This file was generated by SableCC (http://www.sablecc.org/). */

package equivalence.node;

import equivalence.analysis.*;

@SuppressWarnings("nls")
public final class ANilTerm extends PTerm
{
    private TNil _nil_;

    public ANilTerm()
    {
        // Constructor
    }

    public ANilTerm(
        @SuppressWarnings("hiding") TNil _nil_)
    {
        // Constructor
        setNil(_nil_);

    }

    @Override
    public Object clone()
    {
        return new ANilTerm(
            cloneNode(this._nil_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANilTerm(this);
    }

    public TNil getNil()
    {
        return this._nil_;
    }

    public void setNil(TNil node)
    {
        if(this._nil_ != null)
        {
            this._nil_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nil_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nil_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nil_ == child)
        {
            this._nil_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nil_ == oldChild)
        {
            setNil((TNil) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
