/* This file was generated by SableCC (http://www.sablecc.org/). */

package equivalence.node;

import equivalence.analysis.*;

@SuppressWarnings("nls")
public final class TCnot extends Token
{
    public TCnot()
    {
        super.setText("CNOT");
    }

    public TCnot(int line, int pos)
    {
        super.setText("CNOT");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCnot(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCnot(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCnot text.");
    }
}
