/* This file was generated by SableCC (http://www.sablecc.org/). */

package equivalence.node;

import equivalence.analysis.*;

@SuppressWarnings("nls")
public final class TNewqubit extends Token
{
    public TNewqubit()
    {
        super.setText("newqubit");
    }

    public TNewqubit(int line, int pos)
    {
        super.setText("newqubit");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNewqubit(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNewqubit(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNewqubit text.");
    }
}
