/* This file was generated by SableCC (http://www.sablecc.org/). */

package equivalence.node;

import equivalence.analysis.*;

@SuppressWarnings("nls")
public final class TY extends Token
{
    public TY()
    {
        super.setText("Y");
    }

    public TY(int line, int pos)
    {
        super.setText("Y");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TY(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTY(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TY text.");
    }
}
